# Generated by Django 4.1 on 2022-09-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fechanac',
            field=models.DateField(default=-69),
            preserve_default=False,
        ),
    ]
