# Generated by Django 4.1 on 2022-09-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parientes', '0002_familia_fechanac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='fechanac',
        ),
    ]
